Nama : Raafi Nur Adzani   
NIM  : A11.2021.13536 

# Mengimport Library

In [1]:
import numpy as np
import pandas as pd
from sklearn import tree

1. Library 'numpy' digunakan untuk komputasi numerik
2. Library 'matplotlib' digunakan untuk visualisasi data
3. Library 'pandas' digunakan untuk memanipulasi dan analisis data

# Mengimport Dataset 

In [2]:
data = pd.read_csv('purchase_data_exe.csv', delimiter=",", header=0)
data.head()

date  customer_id  product_category payment_method  value [USD]  \
0  20/11/2018        37077               505         credit        49.53   
1  20/11/2018        59173               509         paypal        50.61   
2  20/11/2018        41066               507         credit        85.99   
3  20/11/2018        50741               506         credit        34.60   
4  20/11/2018        53639               515         paypal       266.27   

   time_on_site [Minutes]  clicks_in_site  Unnamed: 7  
0                    12.0               8         NaN  
1                    25.9               8         NaN  
2                    34.9              11         NaN  
3                    16.5               9         NaN  
4                    43.1              30         NaN

tampung data csv 'purchase_data_exe.csv' dalam variable 'data' dan tampilkan 5 data teratas

# Mengubah Data String menjadi Unique-Integer

In [3]:
data["payment_method"] = pd.factorize(data.payment_method)[0]

In [4]:
print(data)

             date  customer_id  product_category  payment_method  value [USD]  \
0      20/11/2018        37077               505               0        49.53   
1      20/11/2018        59173               509               1        50.61   
2      20/11/2018        41066               507               0        85.99   
3      20/11/2018        50741               506               0        34.60   
4      20/11/2018        53639               515               1       266.27   
...           ...          ...               ...             ...          ...   
24994  29/11/2018        33699               513               0        55.89   
24995  29/11/2018        38652               501               1       136.27   
24996  29/11/2018        30222               504               1       427.45   
24997  29/11/2018        30183               507               0       981.81   
24998  29/11/2018        46662               505               0         6.10   

       time_on_site [Minute

# Meghapus Data yang Tidak Diperlukan

In [5]:
data = data.drop(labels="date", axis=1)
data = data.drop(labels="value [USD]", axis=1)
data = data.drop(labels="time_on_site [Minutes]", axis=1)
data = data.drop(labels="clicks_in_site", axis=1)
data = data.drop(labels="Unnamed: 7", axis=1)

In [6]:
print(data)

       customer_id  product_category  payment_method
0            37077               505               0
1            59173               509               1
2            41066               507               0
3            50741               506               0
4            53639               515               1
...            ...               ...             ...
24994        33699               513               0
24995        38652               501               1
24996        30222               504               1
24997        30183               507               0
24998        46662               505               0

[24999 rows x 3 columns]


# Mengubah Data kebentuk numpy

In [7]:
data = data.to_numpy()

In [8]:
print(data)

[[37077   505     0]
 [59173   509     1]
 [41066   507     0]
 ...
 [30222   504     1]
 [30183   507     0]
 [46662   505     0]]


# Membagi Dataset untuk Train dan Test

In [10]:
dataTraning = np.concatenate((data[0:40, :], data[50:90, :]), axis =0)
dataTraning = np.concatenate((data[40:50, :], data[90:100, :]), axis =0)

# Membagi Dataset untuk Input dan Label

In [13]:
inputTraining = dataTraning[:, 0:2]
inputTesting = dataTraning[:, 0:2]
labelTraining = dataTraning[:, 0]
labelTesting = dataTraning [:, 0]

# Mendefinisikan Decision Tree Classifier

In [14]:
model = tree.DecisionTreeClassifier()

# Mentraining Model

In [15]:
model = model.fit(inputTraining, labelTraining)

# Memprediksi Input

In [16]:
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [30549 50606 42084 52161 32218 36491 12227 13196 50444 24528 54446 55746
 58534 53957 53395 52267 29085 56399 27009 35336]
Hasil Prediksi :  [30549 50606 42084 52161 32218 36491 12227 13196 50444 24528 54446 55746
 58534 53957 53395 52267 29085 56399 27009 35336]


In [17]:
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print ("Prediksi Benar : ", prediksiBenar, "data")
print ("Prediksi Salah : ", prediksiSalah, "data")
print("Akurasi : ", prediksiBenar/(prediksiBenar+prediksiSalah)*100, "%")

Prediksi Benar :  20 data
Prediksi Salah :  0 data
Akurasi :  100.0 %
